service: feed-poller

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true
  snsTopic: 'feed-update-${self:provider.stage}'

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-2
  profile: serverless
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:sns:${self:provider.region}:'
            - Ref: AWS::AccountId
            - ':${self:custom.snsTopic}'
    - Effect: Allow
      Action:
        - dynamodb:Scan
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:dynamodb:${self:provider.region}:'
            - Ref: AWS::AccountId
            - ':table/'
            - Ref: feedsTable

functions:
  grabber:
    handler: functions/feed-grabber.main
    # events:
    #   - schedule: rate(12 hours)
    environment:
      SNS_TOPIC_ARN:
        Fn::Join:
          - ':'
          - - 'arn:aws:sns:${self:provider.region}:'
            - Ref: AWS::AccountId
            - ':${self:custom.snsTopic}'
  parser:
    handler: functions/feed-parser.main
    events:
      - sns: ${self:custom.snsTopic}
  # updater:
  #   handler: feed-updater.main
  #   events:
  #     - stream:
  #         type: dynamodb
  #         arn:
  #           Fn::GetAtt:
  #             - worksTable
  #             - StreamArn

resources:
  Resources:
    feedsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Feeds
        AttributeDefinitions:
          - AttributeName: Url
            AttributeType: S
          - AttributeName: LastUpdated
            AttributeType: N
        KeySchema:
          - AttributeName: Url
            KeyType: HASH
          - AttributeName: LastUpdated
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 1
#     userFeedsTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         TableName: UsersFeeds
#         AttributeDefinitions:
#           - AttributeName: User
#             AttributeType: S
#           - AttributeName: Feed
#             AttributeType: S
#         KeySchema:
#           - AttributeName: User
#             KeyType: HASH
#           - AttributeName: Feed
#             KeyType: RANGE
#         ProvisionedThroughput:
#           ReadCapacityUnits: 5
#           WriteCapacityUnits: 5
#     worksTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         TableName: Works
#         AttributeDefinitions:
#           - AttributeName: Url
#             AttributeType: S
#         KeySchema:
#           - AttributeName: Url
#             KeyType: HASH
#         ProvisionedThroughput:
#           ReadCapacityUnits: 5
#           WriteCapacityUnits: 5