service: feed-poller

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  regions: us-east-2

functions:
  hello:
    handler: handler.hello
